# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from jupyter_cpp_wrapperkernel.vin import vin_pb2 as jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2


class FuseVinStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePuppet = channel.unary_unary(
                '/vin.FuseVin/CreatePuppet',
                request_serializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.Empty.SerializeToString,
                response_deserializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.CreatePuppetReply.FromString,
                )
        self.StartStdinNotify = channel.unary_stream(
                '/vin.FuseVin/StartStdinNotify',
                request_serializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.StartStdinNotifyRequest.SerializeToString,
                response_deserializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.StdinNotify.FromString,
                )
        self.SupplyStdinContent = channel.unary_unary(
                '/vin.FuseVin/SupplyStdinContent',
                request_serializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.StdinContent.SerializeToString,
                response_deserializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.Empty.FromString,
                )
        self.DestroyPuppet = channel.unary_unary(
                '/vin.FuseVin/DestroyPuppet',
                request_serializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.DestroyPuppetRequest.SerializeToString,
                response_deserializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.Empty.FromString,
                )


class FuseVinServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePuppet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStdinNotify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SupplyStdinContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyPuppet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FuseVinServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePuppet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePuppet,
                    request_deserializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.Empty.FromString,
                    response_serializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.CreatePuppetReply.SerializeToString,
            ),
            'StartStdinNotify': grpc.unary_stream_rpc_method_handler(
                    servicer.StartStdinNotify,
                    request_deserializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.StartStdinNotifyRequest.FromString,
                    response_serializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.StdinNotify.SerializeToString,
            ),
            'SupplyStdinContent': grpc.unary_unary_rpc_method_handler(
                    servicer.SupplyStdinContent,
                    request_deserializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.StdinContent.FromString,
                    response_serializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.Empty.SerializeToString,
            ),
            'DestroyPuppet': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyPuppet,
                    request_deserializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.DestroyPuppetRequest.FromString,
                    response_serializer=jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vin.FuseVin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FuseVin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePuppet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vin.FuseVin/CreatePuppet',
            jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.Empty.SerializeToString,
            jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.CreatePuppetReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartStdinNotify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/vin.FuseVin/StartStdinNotify',
            jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.StartStdinNotifyRequest.SerializeToString,
            jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.StdinNotify.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SupplyStdinContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vin.FuseVin/SupplyStdinContent',
            jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.StdinContent.SerializeToString,
            jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyPuppet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vin.FuseVin/DestroyPuppet',
            jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.DestroyPuppetRequest.SerializeToString,
            jupyter__cpp__wrapperkernel_dot_vin_dot_vin__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
