# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jupyter_cpp_wrapperkernel/vin/vin.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'jupyter_cpp_wrapperkernel/vin/vin.proto\x12\x03vin\"5\n\x11\x43reatePuppetReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cvin_filename\x18\x02 \x01(\t\"%\n\x17StartStdinNotifyRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x14\x44\x65stroyPuppetRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\r\n\x0bStdinNotify\"+\n\x0cStdinContent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xf0\x01\n\x07\x46useVin\x12\x32\n\x0c\x43reatePuppet\x12\n.vin.Empty\x1a\x16.vin.CreatePuppetReply\x12\x44\n\x10StartStdinNotify\x12\x1c.vin.StartStdinNotifyRequest\x1a\x10.vin.StdinNotify0\x01\x12\x33\n\x12SupplyStdinContent\x12\x11.vin.StdinContent\x1a\n.vin.Empty\x12\x36\n\rDestroyPuppet\x12\x19.vin.DestroyPuppetRequest\x1a\n.vin.EmptyB\x1aZ\x18tuwien.ac.at/fusevin/vinb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jupyter_cpp_wrapperkernel.vin.vin_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\030tuwien.ac.at/fusevin/vin'
  _CREATEPUPPETREPLY._serialized_start=48
  _CREATEPUPPETREPLY._serialized_end=101
  _STARTSTDINNOTIFYREQUEST._serialized_start=103
  _STARTSTDINNOTIFYREQUEST._serialized_end=140
  _DESTROYPUPPETREQUEST._serialized_start=142
  _DESTROYPUPPETREQUEST._serialized_end=176
  _STDINNOTIFY._serialized_start=178
  _STDINNOTIFY._serialized_end=191
  _STDINCONTENT._serialized_start=193
  _STDINCONTENT._serialized_end=236
  _EMPTY._serialized_start=238
  _EMPTY._serialized_end=245
  _FUSEVIN._serialized_start=248
  _FUSEVIN._serialized_end=488
# @@protoc_insertion_point(module_scope)
